### ISSUE TITLE
Very high ram usage for bicubic upsampling option

### ISSUE THREAD

**Issue by ThomasCusson** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#9]
Hello,

I ran the process on a full S2 tile for about 1h30. All went well, until the progress bar was full, then the process started using a lot of ram, above 100GB, so it crashed because of the lack of memory on my machine.

I relaunched without the "--bicubic" option, and all went well.
It seems that it is because it upscales the whole image at once instead of using chunks, filling up the memory when handling large images.

**Comment by jmichel-otb** [comment]
Fix pushed here : https://github.com/Evoland-Land-Monitoring-Evolution/sentinel2_superresolution/commit/49652ab346c4704eb88a3bf482c17c7c00aa46ff

Can you confirm it works on your side ?

**Comment by ThomasCusson** [comment]
Well, latest commit removed the model :
```
Updating 4517298..49652ab
Fast-forward
...
 {models => src/sentinel2_superresolution/models}/carn_3x3x64g4sw_bootstrap.onnx | Bin
 ...
 7 files changed, 67 insertions(+), 31 deletions(-)

```

So I can't run it anymore

**Comment by jmichel-otb** [comment]
It did not remove the model, it moved it to another folder so that it can be installed by pip. You can find it in `src/sentinel2_superresolution/models/carn_3x3x64g4sw_bootstrap.onnx`.

Alternatively, if you re-install following the latest directions, it should work without providing the model to the command-line:

`$ pip install git+https://framagit.org/jmichel-otb/sentinel2_superresolution.git`

or
`$ pip install "sentinel2_superresolution[gpu] @ git+https://github.com/Evoland-Land-Monitoring-Evolution/sentinel2_superresolution.git"`

(from updated README)

**Comment by ThomasCusson** [comment]
Yes, sorry I wasn't paying attention, I removed my previous message.
I'm currently re-running it with the "--bicubic" option, I'll notice you if it worked.

**Comment by ThomasCusson** [comment]
Yes, I forgot to notice you.
